// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// VENDORED from /home/dwyly/code/vaultra/blockchain/contracts/VaultraEscrow.sol.
// Used only by the integration test in test/AegisVaultraIntegration.test.ts to
// prove the VaultraAdapter actually fits the real Vaultra surface. If Vaultra
// evolves its public API, refresh this file from the upstream repo.

import {IERC20} from "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import {SafeERC20} from "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import {ReentrancyGuard} from "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";
import {Ownable2Step} from "@openzeppelin/contracts/access/Ownable2Step.sol";

/**
 * @title VaultraEscrow
 * @notice USDC-denominated escrow contract.
 *
 * Fee model (client pays `amount + 5%` at funding):
 *   - 2.5% platform fee — always paid to Vaultra at completion. Non-refundable.
 *   - 2.5% dispute collateral — refunded to client on clean completion;
 *     if any dispute is filed, it's paid to the arbiter instead.
 *
 * If a dispute is raised, the worker also forfeits 2.5% of the total (taken
 * from their payout on first dispute resolution). The arbiter therefore
 * earns up to 5% of the total (2.5% from client's collateral + 2.5% deducted
 * from worker's share) as compensation for their work.
 *
 * This is "symmetric dispute fee" — both parties always contribute 2.5%
 * when anyone files, regardless of how the arbiter rules, to disincentivize
 * frivolous disputes. The platform's 2.5% is always preserved.
 *
 * @dev Uses SafeERC20 + ReentrancyGuard. Ownership is Ownable2Step.
 */
contract VaultraEscrow is Ownable2Step, ReentrancyGuard {
    using SafeERC20 for IERC20;

    // 25 / 1000 = 2.5%.
    uint256 public constant FEE_PERCENTAGE = 25;              // Platform fee
    uint256 public constant DISPUTE_FEE_PERCENTAGE = 25;      // Each party's dispute cut
    uint256 public constant FEE_DENOMINATOR = 1000;
    uint256 public constant MAX_MILESTONES = 50;

    IERC20 public immutable token;
    address public eclipseDAO;
    uint256 private _nextEscrowNonce;

    enum Status {
        Active,
        Completed,
        Disputed,
        Cancelled
    }

    enum MilestoneStatus {
        Pending,
        Released,
        Disputed
    }

    struct Milestone {
        string title;
        uint256 amount;
        string requirements;
        MilestoneStatus status;
    }

    struct Escrow {
        string title;
        string description;
        address client;
        address worker;
        address arbiter;
        uint256 totalAmount;
        uint256 releasedAmount;
        uint256 feeAmount;             // 2.5% platform fee — held, paid to Vaultra at completion
        uint256 disputeCollateral;     // 2.5% — refunded to client (clean) or paid to arbiter (disputed)
        Status status;
        uint256 createdAt;
        bool hasMilestones;
        bool disputeOccurred;          // set true on first raiseDispute*
        bool disputeCollateralPaid;    // set true when client collateral has been paid to arbiter
        bool platformFeePaid;          // set true when platform has received the 2.5%
        bool collateralSettled;        // set true when dispute collateral has been refunded/paid
        uint256 workerDisputeFeePaid;  // worker-side dispute fee already collected for arbiter
        bytes32 proposalDigest;        // EIP-712 digest of the signed Vaultra proposal
        Milestone[] milestones;
    }

    mapping(bytes32 => Escrow) private _escrows;

    /// @notice EIP-712 digest of the arbiter's signed rationale, recorded
    /// at resolution time. Stored in a parallel mapping (not on `Escrow`)
    /// so the autogenerated `getEscrow()` tuple shape is unchanged.
    mapping(bytes32 => bytes32) private _rationaleDigests;

    event EscrowCreated(
        bytes32 indexed escrowId,
        address indexed client,
        address indexed worker,
        uint256 amount,
        bool hasMilestones,
        bytes32 proposalDigest
    );
    event MilestoneReleased(bytes32 indexed escrowId, uint256 milestoneIndex, uint256 amount);
    event FullAmountReleased(bytes32 indexed escrowId, uint256 amount);
    event DisputeRaised(bytes32 indexed escrowId, uint256 milestoneIndex);
    event DisputeRaisedNoMilestone(bytes32 indexed escrowId);
    event DisputeResolved(
        bytes32 indexed escrowId,
        uint256 milestoneIndex,
        address winner,
        uint256 clientAmount,
        uint256 workerAmount,
        bytes32 rationaleDigest
    );
    event DisputeResolvedNoMilestone(
        bytes32 indexed escrowId,
        address winner,
        uint256 clientAmount,
        uint256 workerAmount,
        bytes32 rationaleDigest
    );
    event EscrowCompleted(bytes32 indexed escrowId);
    event EscrowCancelled(bytes32 indexed escrowId);
    event EclipseDAOUpdated(address indexed previous, address indexed next);

    error ZeroAddress();
    error ClientCannotBeWorker();
    error ArbiterCannotBeParty();
    error EmptyMilestones();
    error TooManyMilestones();
    error MilestoneArrayLengthMismatch();
    error MilestoneAmountZero();
    error AmountZero();
    error NotClient();
    error NotArbiter();
    error NotParty();
    error NotActive();
    error NotDisputed();
    error HasMilestones();
    error NoMilestones();
    error InvalidMilestoneIndex();
    error MilestoneNotPending();
    error MilestoneNotDisputed();
    error AlreadyReleased();
    error InvalidPercentage();

    constructor(IERC20 _token, address _eclipseDAO, address _initialOwner) Ownable(_initialOwner) {
        if (address(_token) == address(0)) revert ZeroAddress();
        if (_eclipseDAO == address(0)) revert ZeroAddress();
        if (_initialOwner == address(0)) revert ZeroAddress();
        token = _token;
        eclipseDAO = _eclipseDAO;
    }

    // ============================================================
    // Creation
    // ============================================================

    /**
     * @notice Create an escrow split into milestones. The caller must have approved
     *         this contract to spend `sum(milestoneAmounts) + fee` of `token`.
     */
    function createEscrowWithMilestones(
        string calldata _title,
        string calldata _description,
        address _worker,
        address _arbiter,
        string[] calldata _milestoneTitles,
        uint256[] calldata _milestoneAmounts,
        string[] calldata _milestoneRequirements,
        bytes32 _proposalDigest
    ) external nonReentrant returns (bytes32) {
        if (_worker == address(0)) revert ZeroAddress();
        if (_worker == msg.sender) revert ClientCannotBeWorker();
        address resolvedArbiter = _arbiter == address(0) ? eclipseDAO : _arbiter;
        if (resolvedArbiter == msg.sender || resolvedArbiter == _worker) {
            revert ArbiterCannotBeParty();
        }
        uint256 n = _milestoneTitles.length;
        if (n == 0) revert EmptyMilestones();
        if (n > MAX_MILESTONES) revert TooManyMilestones();
        if (_milestoneAmounts.length != n || _milestoneRequirements.length != n) {
            revert MilestoneArrayLengthMismatch();
        }

        uint256 totalAmount = 0;
        for (uint256 i = 0; i < n; i++) {
            uint256 amt = _milestoneAmounts[i];
            if (amt == 0) revert MilestoneAmountZero();
            totalAmount += amt;
        }

        uint256 feeAmount = (totalAmount * FEE_PERCENTAGE) / FEE_DENOMINATOR;
        uint256 disputeCollateral = (totalAmount * DISPUTE_FEE_PERCENTAGE) / FEE_DENOMINATOR;
        bytes32 escrowId = _generateId(msg.sender, _worker, _title);

        Escrow storage newEscrow = _escrows[escrowId];
        newEscrow.title = _title;
        newEscrow.description = _description;
        newEscrow.client = msg.sender;
        newEscrow.worker = _worker;
        newEscrow.arbiter = resolvedArbiter;
        newEscrow.totalAmount = totalAmount;
        newEscrow.feeAmount = feeAmount;
        newEscrow.disputeCollateral = disputeCollateral;
        newEscrow.status = Status.Active;
        newEscrow.createdAt = block.timestamp;
        newEscrow.hasMilestones = true;
        newEscrow.proposalDigest = _proposalDigest;

        for (uint256 i = 0; i < n; i++) {
            newEscrow.milestones.push(
                Milestone({
                    title: _milestoneTitles[i],
                    amount: _milestoneAmounts[i],
                    requirements: _milestoneRequirements[i],
                    status: MilestoneStatus.Pending
                })
            );
        }

        // Pull principal + 2.5% platform fee + 2.5% dispute collateral (5% total).
        token.safeTransferFrom(
            msg.sender,
            address(this),
            totalAmount + feeAmount + disputeCollateral
        );

        emit EscrowCreated(escrowId, msg.sender, _worker, totalAmount, true, _proposalDigest);
        return escrowId;
    }

    /**
     * @notice Create a lump-sum escrow (no milestones). Caller must have approved
     *         this contract to spend `_amount + fee` of `token`.
     */
    function createEscrow(
        string calldata _title,
        string calldata _description,
        address _worker,
        address _arbiter,
        uint256 _amount,
        bytes32 _proposalDigest
    ) external nonReentrant returns (bytes32) {
        if (_worker == address(0)) revert ZeroAddress();
        if (_worker == msg.sender) revert ClientCannotBeWorker();
        address resolvedArbiter = _arbiter == address(0) ? eclipseDAO : _arbiter;
        if (resolvedArbiter == msg.sender || resolvedArbiter == _worker) {
            revert ArbiterCannotBeParty();
        }
        if (_amount == 0) revert AmountZero();

        uint256 feeAmount = (_amount * FEE_PERCENTAGE) / FEE_DENOMINATOR;
        uint256 disputeCollateral = (_amount * DISPUTE_FEE_PERCENTAGE) / FEE_DENOMINATOR;
        bytes32 escrowId = _generateId(msg.sender, _worker, _title);

        Escrow storage newEscrow = _escrows[escrowId];
        newEscrow.title = _title;
        newEscrow.description = _description;
        newEscrow.client = msg.sender;
        newEscrow.worker = _worker;
        newEscrow.arbiter = resolvedArbiter;
        newEscrow.totalAmount = _amount;
        newEscrow.feeAmount = feeAmount;
        newEscrow.disputeCollateral = disputeCollateral;
        newEscrow.status = Status.Active;
        newEscrow.createdAt = block.timestamp;
        newEscrow.hasMilestones = false;
        newEscrow.proposalDigest = _proposalDigest;

        token.safeTransferFrom(msg.sender, address(this), _amount + feeAmount + disputeCollateral);

        emit EscrowCreated(escrowId, msg.sender, _worker, _amount, false, _proposalDigest);
        return escrowId;
    }

    // ============================================================
    // Release
    // ============================================================

    function releaseMilestone(bytes32 _escrowId, uint256 _milestoneIndex) external nonReentrant {
        Escrow storage escrow = _escrows[_escrowId];
        if (escrow.client != msg.sender) revert NotClient();
        if (escrow.status != Status.Active) revert NotActive();
        if (!escrow.hasMilestones) revert NoMilestones();
        if (_milestoneIndex >= escrow.milestones.length) revert InvalidMilestoneIndex();

        Milestone storage milestone = escrow.milestones[_milestoneIndex];
        if (milestone.status != MilestoneStatus.Pending) revert MilestoneNotPending();

        milestone.status = MilestoneStatus.Released;
        escrow.releasedAmount += milestone.amount;

        bool allReleased = _allMilestonesReleased(escrow);
        if (allReleased) {
            escrow.status = Status.Completed;
        }

        uint256 workerAmount = _deductWorkerDisputeFee(escrow, milestone.amount);
        if (workerAmount > 0) token.safeTransfer(escrow.worker, workerAmount);

        emit MilestoneReleased(_escrowId, _milestoneIndex, milestone.amount);
        if (allReleased) {
            _settleCompletion(escrow);
            emit EscrowCompleted(_escrowId);
        }
    }

    function releaseFullAmount(bytes32 _escrowId) external nonReentrant {
        Escrow storage escrow = _escrows[_escrowId];
        if (escrow.client != msg.sender) revert NotClient();
        if (escrow.status != Status.Active) revert NotActive();
        if (escrow.hasMilestones) revert HasMilestones();
        if (escrow.releasedAmount != 0) revert AlreadyReleased();

        uint256 amount = escrow.totalAmount;
        escrow.releasedAmount = amount;
        escrow.status = Status.Completed;

        token.safeTransfer(escrow.worker, amount);

        emit FullAmountReleased(_escrowId, amount);
        _settleCompletion(escrow);
        emit EscrowCompleted(_escrowId);
    }

    // ============================================================
    // Disputes
    // ============================================================

    function raiseDispute(bytes32 _escrowId, uint256 _milestoneIndex) external {
        Escrow storage escrow = _escrows[_escrowId];
        if (msg.sender != escrow.client && msg.sender != escrow.worker) revert NotParty();
        if (escrow.status != Status.Active) revert NotActive();
        if (!escrow.hasMilestones) revert NoMilestones();
        if (_milestoneIndex >= escrow.milestones.length) revert InvalidMilestoneIndex();
        Milestone storage m = escrow.milestones[_milestoneIndex];
        if (m.status != MilestoneStatus.Pending) revert MilestoneNotPending();

        m.status = MilestoneStatus.Disputed;
        escrow.status = Status.Disputed;
        escrow.disputeOccurred = true;

        emit DisputeRaised(_escrowId, _milestoneIndex);
    }

    function raiseDisputeNoMilestone(bytes32 _escrowId) external {
        Escrow storage escrow = _escrows[_escrowId];
        if (msg.sender != escrow.client && msg.sender != escrow.worker) revert NotParty();
        if (escrow.status != Status.Active) revert NotActive();
        if (escrow.hasMilestones) revert HasMilestones();
        if (escrow.releasedAmount != 0) revert AlreadyReleased();

        escrow.status = Status.Disputed;
        escrow.disputeOccurred = true;
        emit DisputeRaisedNoMilestone(_escrowId);
    }

    function resolveDispute(
        bytes32 _escrowId,
        uint256 _milestoneIndex,
        uint256 _clientPercentage,
        bytes32 _rationaleDigest
    ) external nonReentrant {
        Escrow storage escrow = _escrows[_escrowId];
        if (msg.sender != escrow.arbiter) revert NotArbiter();
        if (escrow.status != Status.Disputed) revert NotDisputed();
        if (!escrow.hasMilestones) revert NoMilestones();
        if (_milestoneIndex >= escrow.milestones.length) revert InvalidMilestoneIndex();
        if (_clientPercentage > 100) revert InvalidPercentage();

        Milestone storage milestone = escrow.milestones[_milestoneIndex];
        if (milestone.status != MilestoneStatus.Disputed) revert MilestoneNotDisputed();

        uint256 clientAmount = (milestone.amount * _clientPercentage) / 100;
        uint256 workerAmount = milestone.amount - clientAmount;

        milestone.status = MilestoneStatus.Released;
        escrow.releasedAmount += milestone.amount;

        bool allReleased = _allMilestonesReleased(escrow);
        escrow.status = allReleased ? Status.Completed : Status.Active;

        // Pay client-side collateral once, and collect the worker-side
        // dispute fee from this or later worker payouts.
        workerAmount = _settleDisputeArbiter(escrow, workerAmount);

        if (clientAmount > 0) token.safeTransfer(escrow.client, clientAmount);
        if (workerAmount > 0) token.safeTransfer(escrow.worker, workerAmount);

        _rationaleDigests[_escrowId] = _rationaleDigest;
        address winner = _clientPercentage > 50 ? escrow.client : escrow.worker;
        emit DisputeResolved(
            _escrowId,
            _milestoneIndex,
            winner,
            clientAmount,
            workerAmount,
            _rationaleDigest
        );
        if (allReleased) {
            _settleCompletion(escrow);
            emit EscrowCompleted(_escrowId);
        }
    }

    function resolveDisputeNoMilestone(
        bytes32 _escrowId,
        uint256 _clientPercentage,
        bytes32 _rationaleDigest
    ) external nonReentrant {
        Escrow storage escrow = _escrows[_escrowId];
        if (msg.sender != escrow.arbiter) revert NotArbiter();
        if (escrow.status != Status.Disputed) revert NotDisputed();
        if (escrow.hasMilestones) revert HasMilestones();
        if (_clientPercentage > 100) revert InvalidPercentage();

        uint256 clientAmount = (escrow.totalAmount * _clientPercentage) / 100;
        uint256 workerAmount = escrow.totalAmount - clientAmount;

        escrow.releasedAmount = escrow.totalAmount;
        escrow.status = Status.Completed;

        workerAmount = _settleDisputeArbiter(escrow, workerAmount);

        if (clientAmount > 0) token.safeTransfer(escrow.client, clientAmount);
        if (workerAmount > 0) token.safeTransfer(escrow.worker, workerAmount);

        _settleCompletion(escrow);

        _rationaleDigests[_escrowId] = _rationaleDigest;
        address winner = _clientPercentage > 50 ? escrow.client : escrow.worker;
        emit DisputeResolvedNoMilestone(
            _escrowId,
            winner,
            clientAmount,
            workerAmount,
            _rationaleDigest
        );
        emit EscrowCompleted(_escrowId);
    }

    // ============================================================
    // Fee settlement
    // ============================================================

    /**
     * Pays the arbiter the client's upfront dispute collateral once, then
     * deducts the worker-side dispute fee from current/future worker payouts
     * until the worker has contributed up to the same 2.5% amount.
     *
     * If the current worker payout is smaller than the remaining 2.5% cut,
     * we take whatever is available and keep collecting from later milestone
     * payouts. The arbiter's total compensation is therefore up to 5% of the
     * escrow total when worker payouts are available.
     */
    function _settleDisputeArbiter(Escrow storage escrow, uint256 workerAmount)
        private
        returns (uint256 reducedWorkerAmount)
    {
        if (!escrow.disputeCollateralPaid) {
            escrow.disputeCollateralPaid = true;
            escrow.collateralSettled = true; // collateral is being consumed, not refunded
            if (escrow.disputeCollateral > 0) {
                token.safeTransfer(escrow.arbiter, escrow.disputeCollateral);
            }
        }
        return _deductWorkerDisputeFee(escrow, workerAmount);
    }

    function _deductWorkerDisputeFee(Escrow storage escrow, uint256 workerAmount)
        private
        returns (uint256 reducedWorkerAmount)
    {
        if (!escrow.disputeOccurred) return workerAmount;
        if (escrow.workerDisputeFeePaid >= escrow.disputeCollateral) {
            return workerAmount;
        }

        uint256 remainingCut = escrow.disputeCollateral - escrow.workerDisputeFeePaid;
        uint256 workerCut = remainingCut > workerAmount ? workerAmount : remainingCut;
        if (workerCut == 0) return workerAmount;

        escrow.workerDisputeFeePaid += workerCut;
        token.safeTransfer(escrow.arbiter, workerCut);
        return workerAmount - workerCut;
    }

    /**
     * Settles escrow-level obligations at completion:
     *   - Platform fee (2.5%) → Vaultra (always).
     *   - Dispute collateral (2.5%) → refunded to client if no dispute ever
     *     occurred; already consumed by `_settleDisputeArbiter` otherwise.
     * Idempotent.
     */
    function _settleCompletion(Escrow storage escrow) private {
        if (!escrow.platformFeePaid) {
            escrow.platformFeePaid = true;
            if (escrow.feeAmount > 0) {
                token.safeTransfer(owner(), escrow.feeAmount);
            }
        }
        if (!escrow.collateralSettled) {
            escrow.collateralSettled = true;
            // Clean completion: collateral goes back to the client.
            if (escrow.disputeCollateral > 0) {
                token.safeTransfer(escrow.client, escrow.disputeCollateral);
            }
        }
    }

    // ============================================================
    // Admin
    // ============================================================

    function updateEclipseDAO(address _newEclipseDAO) external onlyOwner {
        if (_newEclipseDAO == address(0)) revert ZeroAddress();
        address prev = eclipseDAO;
        eclipseDAO = _newEclipseDAO;
        emit EclipseDAOUpdated(prev, _newEclipseDAO);
    }

    // ============================================================
    // Views
    // ============================================================

    function getEscrow(bytes32 _escrowId)
        external
        view
        returns (
            string memory title,
            string memory description,
            address client,
            address worker,
            address arbiter,
            uint256 totalAmount,
            uint256 releasedAmount,
            uint256 feeAmount,
            Status status,
            uint256 createdAt,
            bool hasMilestones,
            uint256 milestonesCount
        )
    {
        Escrow storage e = _escrows[_escrowId];
        return (
            e.title,
            e.description,
            e.client,
            e.worker,
            e.arbiter,
            e.totalAmount,
            e.releasedAmount,
            e.feeAmount,
            e.status,
            e.createdAt,
            e.hasMilestones,
            e.milestones.length
        );
    }

    function getMilestone(bytes32 _escrowId, uint256 _milestoneIndex)
        external
        view
        returns (string memory title, uint256 amount, MilestoneStatus status)
    {
        Escrow storage e = _escrows[_escrowId];
        if (!e.hasMilestones) revert NoMilestones();
        if (_milestoneIndex >= e.milestones.length) revert InvalidMilestoneIndex();
        Milestone storage m = e.milestones[_milestoneIndex];
        return (m.title, m.amount, m.status);
    }

    function getMilestoneRequirements(bytes32 _escrowId, uint256 _milestoneIndex)
        external
        view
        returns (string memory)
    {
        Escrow storage e = _escrows[_escrowId];
        if (!e.hasMilestones) revert NoMilestones();
        if (_milestoneIndex >= e.milestones.length) revert InvalidMilestoneIndex();
        return e.milestones[_milestoneIndex].requirements;
    }

    function getProposalDigest(bytes32 _escrowId) external view returns (bytes32) {
        return _escrows[_escrowId].proposalDigest;
    }

    function getRationaleDigest(bytes32 _escrowId) external view returns (bytes32) {
        return _rationaleDigests[_escrowId];
    }

    function quoteFee(uint256 _amount) external pure returns (uint256) {
        return (_amount * FEE_PERCENTAGE) / FEE_DENOMINATOR;
    }

    // ============================================================
    // Internal
    // ============================================================

    function _generateId(address client, address worker, string calldata title) private returns (bytes32) {
        uint256 nonce = _nextEscrowNonce++;
        return keccak256(abi.encode(client, worker, block.timestamp, title, block.number, nonce));
    }

    function _allMilestonesReleased(Escrow storage e) private view returns (bool) {
        uint256 len = e.milestones.length;
        for (uint256 i = 0; i < len; i++) {
            if (e.milestones[i].status != MilestoneStatus.Released) return false;
        }
        return true;
    }
}
